<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSFiWUa5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSFiWUa5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSFiWUa5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSFiWUa5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSFiWUa5\App_KernelDevDebugContainer([
    'container.build_hash' => 'SFiWUa5',
    'container.build_id' => '23b2bd5e',
    'container.build_time' => 1622925520,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSFiWUa5');
