<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVz1JN1x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVz1JN1x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVz1JN1x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVz1JN1x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVz1JN1x\App_KernelDevDebugContainer([
    'container.build_hash' => 'Vz1JN1x',
    'container.build_id' => '3a0d7a71',
    'container.build_time' => 1628606006,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVz1JN1x');
