<?php

namespace ContainerVz1JN1x;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XEFipQ6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xEFipQ6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xEFipQ6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cart' => ['privates', 'App\\Service\\ShoppingCartService', 'getShoppingCartServiceService', false],
            'translator' => ['services', 'translator', 'getTranslatorService', false],
        ], [
            'cart' => 'App\\Service\\ShoppingCartService',
            'translator' => '?',
        ]);
    }
}
